from __future__ import annotations

import argparse
import base64
import os
import sys
import time
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
RENDERER_VERSION = "0.1.0"

SUPPORTED_INPUT_EXTENSIONS = {".png", ".jpg", ".jpeg", ".webp"}
OUTPUT_EXTENSIONS = {
    "png": ".png",
    "jpeg": ".jpg",
    "webp": ".webp",
}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Edit a portrait with the AVATAR aging prompt through "
            "the OpenAI Images API."
        )
    )
    parser.add_argument("--image", type=Path, required=True, help="Path to the original portrait.")
    parser.add_argument("--prompt", type=Path, default=ROOT / "outputs" / "aging_prompt.txt", help="Path to the prompt generated by prompt_builder.py.")
    parser.add_argument("--output", type=Path, default=ROOT / "outputs" / "aged_face.png", help="Path for the edited portrait.")
    parser.add_argument("--model", default="gpt-image-2", help="OpenAI image-editing model.")
    parser.add_argument("--quality", choices=("low", "medium", "high", "auto"), default="medium", help="Output quality. Use low for inexpensive tests.")
    parser.add_argument("--size", choices=("1024x1024", "1024x1536", "1536x1024", "auto"), default="auto", help="Output image dimensions.")
    parser.add_argument("--format", dest="output_format", choices=("png", "jpeg", "webp"), default="png", help="Output file format.")
    return parser.parse_args()


def validate_inputs(args: argparse.Namespace) -> None:
    if not args.image.exists():
        raise FileNotFoundError(f"Portrait not found: {args.image}")
    if not args.image.is_file():
        raise ValueError(f"Portrait path is not a file: {args.image}")
    extension = args.image.suffix.lower()
    if extension not in SUPPORTED_INPUT_EXTENSIONS:
        supported = ", ".join(sorted(SUPPORTED_INPUT_EXTENSIONS))
        raise ValueError(f"Unsupported portrait format '{extension}'. Use one of: {supported}")
    if not args.prompt.exists():
        raise FileNotFoundError(f"Prompt not found: {args.prompt}\nRun `python avatar/prompt_builder.py` first.")
    if not args.prompt.is_file():
        raise ValueError(f"Prompt path is not a file: {args.prompt}")
    if not os.environ.get("OPENAI_API_KEY"):
        raise EnvironmentError("OPENAI_API_KEY is not set.\nPowerShell example:\n  $env:OPENAI_API_KEY=\"your_api_key_here\"")


def load_prompt(prompt_path: Path) -> str:
    prompt = prompt_path.read_text(encoding="utf-8").strip()
    if not prompt:
        raise ValueError(f"Prompt file is empty: {prompt_path}")
    return prompt


def normalize_output_path(output_path: Path, output_format: str) -> Path:
    expected_extension = OUTPUT_EXTENSIONS[output_format]
    if output_path.suffix.lower() != expected_extension:
        output_path = output_path.with_suffix(expected_extension)
    return output_path


def extract_usage(result: Any) -> dict[str, Any] | None:
    usage = getattr(result, "usage", None)
    if usage is None:
        return None
    if hasattr(usage, "model_dump"):
        return usage.model_dump()
    if isinstance(usage, dict):
        return usage
    return None


def render_portrait(*, image_path: Path, prompt: str, output_path: Path, model: str, quality: str, size: str, output_format: str) -> tuple[Path, dict[str, Any] | None]:
    try:
        from openai import OpenAI
    except ImportError as exc:
        raise RuntimeError("The OpenAI Python package is not installed.\nInstall it with:\n  python -m pip install --upgrade openai") from exc

    client_start = time.perf_counter()
    client = OpenAI()
    print(f"[AVATAR PROFILE] OpenAI client init: {time.perf_counter() - client_start:.3f}s", flush=True)

    api_start = time.perf_counter()
    print(f"[AVATAR PROFILE] OpenAI image edit START model={model} quality={quality} size={size}", flush=True)
    try:
        with image_path.open("rb") as image_file:
            result = client.images.edit(
                model=model,
                image=image_file,
                prompt=prompt,
                quality=quality,
                size=size,
                output_format=output_format,
            )
    except Exception as exc:
        print(f"[AVATAR PROFILE] OpenAI image edit FAILED after {time.perf_counter() - api_start:.3f}s", flush=True)
        raise RuntimeError(
            "OpenAI image editing failed. Check the API key, billing, organization verification, input image, and model access.\n"
            f"Original error: {exc}"
        ) from exc
    print(f"[AVATAR PROFILE] OpenAI image edit: {time.perf_counter() - api_start:.3f}s", flush=True)

    if not result.data:
        raise RuntimeError("The Images API returned no image data.")
    encoded_image = result.data[0].b64_json
    if not encoded_image:
        raise RuntimeError("The Images API response did not contain b64_json.")

    decode_start = time.perf_counter()
    try:
        image_bytes = base64.b64decode(encoded_image, validate=True)
    except Exception as exc:
        raise RuntimeError("Could not decode the returned image.") from exc
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_bytes(image_bytes)
    print(f"[AVATAR PROFILE] Decode + write: {time.perf_counter() - decode_start:.3f}s", flush=True)

    return output_path, extract_usage(result)


def main() -> None:
    args = parse_args()
    validate_inputs(args)
    prompt = load_prompt(args.prompt)
    output_path = normalize_output_path(args.output, args.output_format)
    saved_path, usage = render_portrait(image_path=args.image, prompt=prompt, output_path=output_path, model=args.model, quality=args.quality, size=args.size, output_format=args.output_format)
    print(f"AVATAR Image Renderer v{RENDERER_VERSION} completed.")
    print(f"Model:   {args.model}")
    print(f"Input:   {args.image.resolve()}")
    print(f"Prompt:  {args.prompt.resolve()}")
    print(f"Quality: {args.quality}")
    print(f"Size:    {args.size}")
    print(f"Output:  {saved_path.resolve()}")
    if usage:
        print("\nAPI usage:")
        for key, value in usage.items():
            print(f"  {key}: {value}")


if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print("\nRendering cancelled.", file=sys.stderr)
        raise SystemExit(130)
    except Exception as exc:
        print(f"\nERROR: {exc}", file=sys.stderr)
        raise SystemExit(1)
